// Generated by build.py. Server-side price list. Do not edit by hand.
export default {
 "WZ-1001": {
  "name": "Clip-on bird spike strip, 2 ft",
  "price": 32,
  "material": "Polycarbonate spikes, ASA clips",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1001.jpg"
 },
 "WZ-1002": {
  "name": "Spreader bird spinners, pair",
  "price": 51,
  "material": "ASA vanes, 316 SS axle",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1002.jpg"
 },
 "WZ-1003": {
  "name": "Radar arch bird wire kit",
  "price": 102,
  "material": "316 SS wire, ASA posts",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1003.jpg"
 },
 "WZ-1004": {
  "name": "Antenna and outrigger tip cones, set of four",
  "price": 19,
  "material": "ASA, white",
  "leadTime": "1 week",
  "image": "img/products/WZ-1004.jpg"
 },
 "WZ-1005": {
  "name": "Boom-top bird deterrent strip",
  "price": 47,
  "material": "ASA base, SS spikes",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1005.jpg"
 },
 "WZ-1006": {
  "name": "Bimini frame bird clips, set of six",
  "price": 27,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1006.jpg"
 },
 "WZ-1007": {
  "name": "Swim platform sea lion barrier",
  "price": 323,
  "material": "Marine HDPE panels, 316 SS pins",
  "leadTime": "3 to 4 weeks",
  "image": "img/products/WZ-1007.jpg"
 },
 "WZ-1008": {
  "name": "Swim ladder lock-up cover",
  "price": 119,
  "material": "Marine HDPE, 316 SS hinge",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1008.jpg"
 },
 "WZ-1009": {
  "name": "Chartplotter adapter bezel, 7 in. to 9 in.",
  "price": 81,
  "material": "ASA, black",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1009.jpg"
 },
 "WZ-1010": {
  "name": "Binnacle instrument pod, two displays",
  "price": 119,
  "material": "ASA, white or black",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1010.jpg"
 },
 "WZ-1011": {
  "name": "Helm phone and tablet cradle",
  "price": 55,
  "material": "ASA, black",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1011.jpg"
 },
 "WZ-1012": {
  "name": "Shore power plug cover with lock tab",
  "price": 38,
  "material": "ASA with gasket",
  "leadTime": "1 week",
  "image": "img/products/WZ-1012.jpg"
 },
 "WZ-1013": {
  "name": "Shore power cord strain relief clip",
  "price": 24,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 week",
  "image": "img/products/WZ-1013.jpg"
 },
 "WZ-1014": {
  "name": "Rail antenna mount base",
  "price": 64,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1014.jpg"
 },
 "WZ-1015": {
  "name": "Fender rail clips, pair",
  "price": 26,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1015.jpg"
 },
 "WZ-1016": {
  "name": "Cleat-mount fender hanger",
  "price": 29,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 week",
  "image": "img/products/WZ-1016.jpg"
 },
 "WZ-1017": {
  "name": "Anchor chain depth markers, set of ten",
  "price": 27,
  "material": "TPU, color coded",
  "leadTime": "1 week",
  "image": "img/products/WZ-1017.jpg"
 },
 "WZ-1018": {
  "name": "Boat hook holder clips, pair",
  "price": 24,
  "material": "ASA, white",
  "leadTime": "1 week",
  "image": "img/products/WZ-1018.jpg"
 },
 "WZ-1019": {
  "name": "Lifeline line-coil hangers, set of four",
  "price": 22,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1019.jpg"
 },
 "WZ-1020": {
  "name": "Stern rail flagstaff socket",
  "price": 60,
  "material": "316 stainless steel",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1020.jpg"
 },
 "WZ-1021": {
  "name": "Solar panel rail mounts, pair",
  "price": 221,
  "material": "316 stainless steel",
  "leadTime": "3 to 4 weeks",
  "image": "img/products/WZ-1021.jpg"
 },
 "WZ-1022": {
  "name": "Anchor roller guard",
  "price": 153,
  "material": "316 stainless steel",
  "leadTime": "3 to 4 weeks",
  "image": "img/products/WZ-1022.jpg"
 },
 "WZ-1023": {
  "name": "Seacock position tags, set of ten",
  "price": 26,
  "material": "ASA, red and green",
  "leadTime": "1 week",
  "image": "img/products/WZ-1023.jpg"
 },
 "WZ-1024": {
  "name": "Emergency plug holders, set of ten",
  "price": 24,
  "material": "ASA, orange",
  "leadTime": "1 week",
  "image": "img/products/WZ-1024.jpg"
 },
 "WZ-1025": {
  "name": "Bilge float switch guard",
  "price": 27,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1025.jpg"
 },
 "WZ-1026": {
  "name": "Spare impeller and belt caddy",
  "price": 34,
  "material": "PETG, gray",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1026.jpg"
 },
 "WZ-1027": {
  "name": "Raw water strainer bracket",
  "price": 53,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1027.jpg"
 },
 "WZ-1028": {
  "name": "Two-cable deck gland",
  "price": 36,
  "material": "ASA with rubber gasket",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1028.jpg"
 },
 "WZ-1029": {
  "name": "Bulkhead grommet set, six sizes",
  "price": 24,
  "material": "TPU and PETG",
  "leadTime": "1 week",
  "image": "img/products/WZ-1029.jpg"
 },
 "WZ-1030": {
  "name": "Fire port cover",
  "price": 26,
  "material": "ASA, red",
  "leadTime": "1 week",
  "image": "img/products/WZ-1030.jpg"
 },
 "WZ-1031": {
  "name": "Winch covers, pair",
  "price": 76,
  "material": "Solution-dyed marine acrylic canvas",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1031.jpg"
 },
 "WZ-1032": {
  "name": "Helm wheel cover",
  "price": 94,
  "material": "Solution-dyed marine acrylic canvas, shock-cord hem",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1032.jpg"
 },
 "WZ-1033": {
  "name": "Snap-on dock line chafe sleeves, pair",
  "price": 38,
  "material": "Heavy tubular woven polyester, stainless snaps",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1033.jpg"
 },
 "WZ-1034": {
  "name": "Magnetic companionway bug screen",
  "price": 102,
  "material": "No-see-um mesh, sewn-in magnets",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1034.jpg"
 },
 "WZ-1035": {
  "name": "Bimini rain catcher",
  "price": 72,
  "material": "Solution-dyed marine acrylic, PVC hose fitting",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1035.jpg"
 },
 "WZ-1036": {
  "name": "Three-bow bimini",
  "price": 1190,
  "material": "Solution-dyed marine acrylic canvas, 316 SS frame",
  "leadTime": "4 to 6 weeks",
  "image": "img/products/WZ-1036.jpg"
 },
 "WZ-1037": {
  "name": "Cockpit cushion set",
  "price": 935,
  "material": "Closed-cell foam, marine-grade vinyl with leather grain",
  "leadTime": "4 to 6 weeks",
  "image": "img/products/WZ-1037.jpg"
 },
 "WZ-1038": {
  "name": "Center console cover",
  "price": 221,
  "material": "Solution-dyed marine acrylic canvas",
  "leadTime": "3 weeks",
  "image": "img/products/WZ-1038.jpg"
 },
 "WZ-1039": {
  "name": "Overhead hatch hinges, pair",
  "price": 60,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1039.jpg"
 },
 "WZ-1040": {
  "name": "Cockpit locker cam latch",
  "price": 32,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1040.jpg"
 },
 "WZ-1041": {
  "name": "Engine air intake cover",
  "price": 72,
  "material": "Nylon with carbon fiber",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1041.jpg"
 },
 "WZ-1042": {
  "name": "Hatch hold-open stay",
  "price": 41,
  "material": "Nylon with carbon fiber, SS pins",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1042.jpg"
 },
 "WZ-1043": {
  "name": "Swim ladder step",
  "price": 76,
  "material": "316 stainless steel with HDPE tread",
  "leadTime": "3 weeks",
  "image": "img/products/WZ-1043.jpg"
 },
 "WZ-1044": {
  "name": "Windlass foot switch cover",
  "price": 30,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1044.jpg"
 },
 "WZ-1045": {
  "name": "Hull diver scraper holster",
  "price": 32,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 week",
  "image": "img/products/WZ-1045.jpg"
 },
 "WZ-1046": {
  "name": "Rail-mount detailing caddy",
  "price": 81,
  "material": "Marine HDPE",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1046.jpg"
 },
 "WZ-1047": {
  "name": "Yacht manager key board",
  "price": 102,
  "material": "Marine HDPE, engraved",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1047.jpg"
 },
 "WZ-1048": {
  "name": "Anode wear gauge",
  "price": 20,
  "material": "ASA, high-visibility yellow",
  "leadTime": "1 week",
  "image": "img/products/WZ-1048.jpg"
 },
 "WZ-1049": {
  "name": "Dock box hose and cord hanger",
  "price": 51,
  "material": "Marine HDPE",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1049.jpg"
 },
 "WZ-1050": {
  "name": "Crew radio holster, life jacket clip",
  "price": 26,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 week",
  "image": "img/products/WZ-1050.jpg"
 },
 "WZ-1051": {
  "name": "Dock finger sea lion guard",
  "price": 204,
  "material": "Marine HDPE panels, 316 SS brackets",
  "leadTime": "3 to 4 weeks",
  "image": "img/products/WZ-1051.jpg"
 },
 "WZ-1052": {
  "name": "Solar panel edge bird spikes, 4 ft",
  "price": 24,
  "material": "Polycarbonate spikes, ASA clips",
  "leadTime": "1 week",
  "image": "img/products/WZ-1052.jpg"
 },
 "WZ-1053": {
  "name": "Tender sea lion top cover",
  "price": 187,
  "material": "Solution-dyed marine acrylic canvas, shock-cord hem",
  "leadTime": "3 weeks",
  "image": "img/products/WZ-1053.jpg"
 },
 "WZ-1054": {
  "name": "Masthead bird deterrent crown",
  "price": 64,
  "material": "316 SS spikes, ASA base",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1054.jpg"
 },
 "WZ-1055": {
  "name": "Autopilot remote holster",
  "price": 26,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1055.jpg"
 },
 "WZ-1056": {
  "name": "VHF mic relocation bracket",
  "price": 24,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1056.jpg"
 },
 "WZ-1057": {
  "name": "Display sun hood, 9 in",
  "price": 38,
  "material": "ASA, black",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1057.jpg"
 },
 "WZ-1058": {
  "name": "Tablet sun hood with rail clamp",
  "price": 47,
  "material": "ASA, black",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1058.jpg"
 },
 "WZ-1059": {
  "name": "Dual USB-C charge panel bezel",
  "price": 30,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1059.jpg"
 },
 "WZ-1060": {
  "name": "Custom-cut switch panel plate",
  "price": 51,
  "material": "Marine HDPE, engraved",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1060.jpg"
 },
 "WZ-1061": {
  "name": "Lifeline gate latch stop",
  "price": 34,
  "material": "316 stainless steel",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1061.jpg"
 },
 "WZ-1062": {
  "name": "Stanchion sheet chafe guard",
  "price": 20,
  "material": "ASA, white",
  "leadTime": "1 week",
  "image": "img/products/WZ-1062.jpg"
 },
 "WZ-1063": {
  "name": "Boat hook tip replacement",
  "price": 19,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 week",
  "image": "img/products/WZ-1063.jpg"
 },
 "WZ-1064": {
  "name": "Deck fill cap keeper",
  "price": 22,
  "material": "316 SS cable, ASA ring",
  "leadTime": "1 week",
  "image": "img/products/WZ-1064.jpg"
 },
 "WZ-1065": {
  "name": "Mast base halyard organizer",
  "price": 76,
  "material": "Marine HDPE",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1065.jpg"
 },
 "WZ-1066": {
  "name": "Folding rail rod holder",
  "price": 81,
  "material": "316 stainless steel",
  "leadTime": "3 weeks",
  "image": "img/products/WZ-1066.jpg"
 },
 "WZ-1067": {
  "name": "Anchor roller keeper pin",
  "price": 30,
  "material": "316 stainless steel",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1067.jpg"
 },
 "WZ-1068": {
  "name": "Mooring pendant chafe tube",
  "price": 34,
  "material": "Heavy tubular woven polyester, stainless snaps",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1068.jpg"
 },
 "WZ-1069": {
  "name": "Through-hull label rings, set of 12",
  "price": 27,
  "material": "ASA, engraved",
  "leadTime": "1 week",
  "image": "img/products/WZ-1069.jpg"
 },
 "WZ-1070": {
  "name": "Fuel filter drip tray",
  "price": 32,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1070.jpg"
 },
 "WZ-1071": {
  "name": "Battery terminal covers, color coded",
  "price": 19,
  "material": "TPU, red and black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1071.jpg"
 },
 "WZ-1072": {
  "name": "Wire loom P-clips, set of 20",
  "price": 15,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 week",
  "image": "img/products/WZ-1072.jpg"
 },
 "WZ-1073": {
  "name": "Oil change pump bracket",
  "price": 26,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1073.jpg"
 },
 "WZ-1074": {
  "name": "Holding tank vent filter bracket",
  "price": 24,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1074.jpg"
 },
 "WZ-1075": {
  "name": "Large bilge pump strainer cage",
  "price": 29,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1075.jpg"
 },
 "WZ-1076": {
  "name": "Fuel fill spill collar",
  "price": 22,
  "material": "TPU, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1076.jpg"
 },
 "WZ-1077": {
  "name": "Fitted hatch wind scoop",
  "price": 72,
  "material": "Ripstop polyester, acrylic trim",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1077.jpg"
 },
 "WZ-1078": {
  "name": "Rail grill cover",
  "price": 47,
  "material": "Solution-dyed marine acrylic canvas",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1078.jpg"
 },
 "WZ-1079": {
  "name": "Portable fuel tank cover",
  "price": 38,
  "material": "Solution-dyed marine acrylic canvas",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1079.jpg"
 },
 "WZ-1080": {
  "name": "Life ring cover",
  "price": 34,
  "material": "Solution-dyed marine acrylic canvas",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1080.jpg"
 },
 "WZ-1081": {
  "name": "Tender seat cushion with bag",
  "price": 76,
  "material": "Closed-cell foam, marine-grade vinyl with leather grain, acrylic bag",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1081.jpg"
 },
 "WZ-1082": {
  "name": "Lee cloths, pair",
  "price": 128,
  "material": "Heavy woven polyester with nylon webbing",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1082.jpg"
 },
 "WZ-1083": {
  "name": "Portlight covers, set of four",
  "price": 94,
  "material": "Solution-dyed marine acrylic canvas, snap mount",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1083.jpg"
 },
 "WZ-1084": {
  "name": "Jerry can covers, pair",
  "price": 60,
  "material": "Solution-dyed marine acrylic canvas",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1084.jpg"
 },
 "WZ-1085": {
  "name": "Overhead hatch handle",
  "price": 36,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1085.jpg"
 },
 "WZ-1086": {
  "name": "Companionway slide runners",
  "price": 55,
  "material": "Marine HDPE",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1086.jpg"
 },
 "WZ-1087": {
  "name": "Portlight dog lever",
  "price": 24,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 week",
  "image": "img/products/WZ-1087.jpg"
 },
 "WZ-1088": {
  "name": "Marine head pump handle",
  "price": 30,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 week",
  "image": "img/products/WZ-1088.jpg"
 },
 "WZ-1089": {
  "name": "Galley stove knob set",
  "price": 27,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1089.jpg"
 },
 "WZ-1090": {
  "name": "Cabin light lens",
  "price": 15,
  "material": "Translucent PETG",
  "leadTime": "1 week",
  "image": "img/products/WZ-1090.jpg"
 },
 "WZ-1091": {
  "name": "Cockpit table leg bracket",
  "price": 64,
  "material": "316 stainless steel",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1091.jpg"
 },
 "WZ-1092": {
  "name": "Dock line length tags, set of 8",
  "price": 19,
  "material": "ASA, color coded",
  "leadTime": "1 week",
  "image": "img/products/WZ-1092.jpg"
 },
 "WZ-1093": {
  "name": "Floating key tag with ID window",
  "price": 13,
  "material": "Closed-cell foam, ASA window",
  "leadTime": "1 week",
  "image": "img/products/WZ-1093.jpg"
 },
 "WZ-1094": {
  "name": "Dock box checklist board",
  "price": 55,
  "material": "Marine HDPE, engraved",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1094.jpg"
 },
 "WZ-1095": {
  "name": "Diver tool lanyard clip",
  "price": 24,
  "material": "Nylon with carbon fiber",
  "leadTime": "1 week",
  "image": "img/products/WZ-1095.jpg"
 },
 "WZ-1096": {
  "name": "Engine room flashlight holder",
  "price": 19,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1096.jpg"
 },
 "WZ-1097": {
  "name": "Rail brush hanger",
  "price": 20,
  "material": "ASA, white",
  "leadTime": "1 week",
  "image": "img/products/WZ-1097.jpg"
 },
 "WZ-1098": {
  "name": "Dinghy oar clips, pair",
  "price": 22,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1098.jpg"
 },
 "WZ-1099": {
  "name": "Davit strap chafe pads, pair",
  "price": 47,
  "material": "Heavy vinyl-coated polyester, fleece lined",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1099.jpg"
 },
 "WZ-1100": {
  "name": "Tender bow line bag",
  "price": 34,
  "material": "Solution-dyed marine acrylic canvas",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1100.jpg"
 },
 "WZ-1101": {
  "name": "Dock line rat guards, pair",
  "price": 38,
  "material": "ASA, split cone",
  "leadTime": "1 week",
  "image": "img/products/WZ-1101.jpg"
 },
 "WZ-1102": {
  "name": "Cockpit scupper critter guards, set of 4",
  "price": 46,
  "material": "316 SS mesh, ASA frame",
  "leadTime": "1 week",
  "image": "img/products/WZ-1102.jpg"
 },
 "WZ-1103": {
  "name": "Dorade vent bird screens, pair",
  "price": 42,
  "material": "316 SS mesh, ASA ring",
  "leadTime": "1 week",
  "image": "img/products/WZ-1103.jpg"
 },
 "WZ-1104": {
  "name": "Outboard cowling bird guard",
  "price": 55,
  "material": "ASA spike ring, strap mount",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1104.jpg"
 },
 "WZ-1105": {
  "name": "Transducer kelp deflector",
  "price": 64,
  "material": "ASA fairing, 316 SS bolts",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1105.jpg"
 },
 "WZ-1106": {
  "name": "Starlink Mini rail mount with cable gland",
  "price": 110,
  "material": "316 SS clamp, ASA cradle",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1106.jpg"
 },
 "WZ-1107": {
  "name": "Bilge camera bracket",
  "price": 34,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1107.jpg"
 },
 "WZ-1108": {
  "name": "Chain pile knocker",
  "price": 72,
  "material": "316 SS rod, HDPE handle",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1108.jpg"
 },
 "WZ-1109": {
  "name": "Hatch drip gutter",
  "price": 29,
  "material": "Clear PETG",
  "leadTime": "1 week",
  "image": "img/products/WZ-1109.jpg"
 },
 "WZ-1110": {
  "name": "Stanchion base drip collars, set of 4",
  "price": 24,
  "material": "Clear TPU",
  "leadTime": "1 week",
  "image": "img/products/WZ-1110.jpg"
 },
 "WZ-1111": {
  "name": "Boom crutch, custom height",
  "price": 145,
  "material": "Marine HDPE, 316 SS pins",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1111.jpg"
 },
 "WZ-1112": {
  "name": "Spearfishing gun rack for T-top",
  "price": 168,
  "material": "Marine HDPE, 316 SS clamps",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1112.jpg"
 },
 "WZ-1113": {
  "name": "Dive tank rack, 2 or 3 tanks",
  "price": 185,
  "material": "Marine HDPE",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1113.jpg"
 },
 "WZ-1114": {
  "name": "Dock cleat safety caps, set of 4",
  "price": 52,
  "material": "TPU, high-visibility yellow",
  "leadTime": "1 week",
  "image": "img/products/WZ-1114.jpg"
 },
 "WZ-1115": {
  "name": "Engraved service log plate with QR code",
  "price": 48,
  "material": "Marine HDPE, engraved",
  "leadTime": "1 week",
  "image": "img/products/WZ-1115.jpg"
 },
 "WZ-1116": {
  "name": "Dog boarding ramp for swim platform",
  "price": 210,
  "material": "Marine HDPE, traction tread",
  "leadTime": "2 to 3 weeks",
  "image": "img/products/WZ-1116.jpg"
 },
 "WZ-1117": {
  "name": "SUP and kayak lifeline saddles, pair",
  "price": 88,
  "material": "Marine HDPE, webbing straps",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1117.jpg"
 },
 "WZ-1118": {
  "name": "Paddle and pole T-top clips, set of 4",
  "price": 36,
  "material": "ASA, black",
  "leadTime": "1 week",
  "image": "img/products/WZ-1118.jpg"
 },
 "WZ-1119": {
  "name": "Lazy jack line keepers, pair",
  "price": 26,
  "material": "ASA, white",
  "leadTime": "1 week",
  "image": "img/products/WZ-1119.jpg"
 },
 "WZ-1120": {
  "name": "Winch handle floating keeper holster",
  "price": 58,
  "material": "Nylon with carbon fiber, foam float",
  "leadTime": "1 week",
  "image": "img/products/WZ-1120.jpg"
 },
 "WZ-1121": {
  "name": "Pro dock line chafe sleeves, pair",
  "price": 72,
  "material": "Polyurethane-coated tubular polyester, stainless snaps",
  "leadTime": "1 to 2 weeks",
  "image": "img/products/WZ-1121.jpg"
 },
 "WZ-1122": {
  "name": "Pro mooring pendant chafe gear",
  "price": 118,
  "material": "Polyurethane-coated tubular polyester, 316 SS thimble guard",
  "leadTime": "2 weeks",
  "image": "img/products/WZ-1122.jpg"
 }
};
